### ISSUE TITLE
Create helm chart for k8s-reverse-proxy

### ISSUE THREAD

**Issue by faisaladnanpeltops** [k8-proxy/gp-jira-website#2]
Use one of the solution below:
- https://github.com/k8-proxy/k8-reverse-proxy
- https://github.com/k8-proxy/k8-reverse-proxy/tree/master/upwork-devs/MariuszFerdyn/v4-VariableConfigPlusICAP

I want this to be ready by Monday please.

**Comment by dtollaku** [comment]
This is done, we reviewed with @mahnouman and @GINAGC
