### ISSUE TITLE
Document any specifics on deployment for JIRA websites

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/gp-jira-website#7]
Document any specifics on deployment for JIRA websites

**Comment by MariuszFerdyn** [comment]
It is covered here: https://github.com/k8-proxy/gp-jira-website/tree/main/atlassian.net/local-dns-changes

**Comment by GINAGC** [comment]
@mahnouman please assign this one to review the documentation.

**Comment by naderaly** [comment]
Hello @MariuszFerdyn following the steps mentioned in the readme file I found that the porixed website doesn't load well, can u assist 
![image](https://user-images.githubusercontent.com/58347752/99903649-47895600-2cce-11eb-9017-3a15cf451bfc.png)

**Comment by MariuszFerdyn** [comment]
Can you describe it more? What doesn't work. Let's talk over Slack.

**Comment by naderaly** [comment]
@MariuszFerdyn yes sure, but as the attached screenshot is showing that some pictures aren't loaded

**Comment by MariuszFerdyn** [comment]
Can you check source of these picures, Developer View - Network TAB - what happened here?

**Comment by naderaly** [comment]
@MariuszFerdyn I've sent you the screenshot on slack as requested

**Comment by MariuszFerdyn** [comment]
The exac error is:

Document Access Blocked due to Policy
You tried to upload/download a file that does not comply with current policy
The Http location is: https://os-summit.atlassian.net/secure/projectavatar
The error code is: 9
For more information contact your system administrator

So the ICAP return that information. The question is why.

**Comment by naderaly** [comment]
@mahnouman @GINAGC , I have sent a PR for the target repo 
https://github.com/k8-proxy/gp-jira-website/pull/9

**Comment by MariuszFerdyn** [comment]
Problem was connected with License error of local ICAP. Solution is to use external ICAP.

**Comment by GINAGC** [comment]
documentation added to wiki
